resources:
  - name: paas-cf
    type: git-gpg
    source:
      uri: https://github.com/alphagov/paas-cf.git
      branch: {{branch_name}}
      tag_filter: {{paas_cf_tag_filter}}
      commit_verification_key_ids: {{gpg_ids}}

  - name: delete-timer
    type: time
    source:
      start: 20:00 -0000
      stop: 6:00 -0000
      interval: 2h

  - name: bosh-secrets
    type: s3-iam
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      versioned_file: bosh-secrets.yml

jobs:
  - name: delete
    serial: true
    plan:
      - get: delete-timer
        trigger: true
      - get: bosh-secrets
      - get: paas-cf
      - task: delete-deployment
        config:
          platform: linux
          inputs:
            - name: delete-timer
            - name: bosh-secrets
            - name: paas-cf
          image: docker:///governmentpaas/bosh-cli
          run:
            path: sh
            args:
              - -e
              - -c
              # The following sleep monstrosity deterministically sleeps for a
              # period of time between 0-20mins in order to prevent all our
              # deletion jobs running at the same time. See the commit message for
              # how it works.
              - |
                sum=$(echo {{deploy_env}} | md5sum);
                short=${sum:0:15};
                decimal=$((0x$short));
                sleeptime=$((${decimal##-} % 60*20));
                echo "Sleeping for $sleeptime seconds before deletion.."
                sleep $sleeptime
                ./paas-cf/concourse/scripts/bosh_login.sh {{bosh_fqdn}} bosh-secrets/bosh-secrets.yml
                bosh -n delete deployment {{deploy_env}} --force
