meta:
  environment: (( grab terraform_outputs.environment ))

name: (( grab meta.environment ))
director_uuid: ~

releases:
  - name: cf
    version: "253"
    url: https://bosh.io/d/github.com/cloudfoundry/cf-release?v=253
    sha1: 8e0ea926929bdb1ff16a366e2154d017c637a137
  - name: diego
    version: 1.8.1
    url: https://bosh.io/d/github.com/cloudfoundry/diego-release?v=1.8.1
    sha1: a8c9fdecf59a1fceb2837ac0cfbde6a939427adb
  - name: garden-runc
    version: 1.2.0
    url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.2.0
    sha1: 37d46f41d187dbd90e1bf0748fa5c1fb60870bff
  - name: cflinuxfs2-rootfs
    version: 1.53.0
    url: https://bosh.io/d/github.com/cloudfoundry/cflinuxfs2-rootfs-release?v=1.53.0
    sha1: 93950d5d2071fdb395b7b1c958b8abddb8fdcfa0
  - name: paas-haproxy
    version: 0.1.3
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/paas-haproxy-0.1.3.tgz
    sha1: 732ceb817afe33ee117b85a202d87f6f5c3dd760
  - name: datadog-for-cloudfoundry
    version: 0.1.13
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/datadog-for-cloudfoundry-0.1.13.tgz
    sha1: b5846e6bb476ac76725ceac62ef5d512de6b46dd
  - name: ipsec
    version: 0.1.1
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/ipsec-0.1.1.tgz
    sha1: c091d8bd1b982176904b3cea8a13a6d3dbf7642b

stemcells:
  - alias: default
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: "3363.10"

update:
  canaries: 0
  max_in_flight: 1
  canary_watch_time: 30000-420000
  update_watch_time: 5000-420000
  serial: false
