---

vm_extensions:

  - name: ssh_proxy_elb
    cloud_properties:
      elbs:
        - (( grab terraform_outputs.cf_ssh_proxy_elb_name ))

  - name: cf_rds_client
    cloud_properties:
      security_groups:
        - (( grab terraform_outputs.default_security_group ))
        - (( grab terraform_outputs.cf_rds_client_security_group ))
